[toolchain]

[features]
resolution = true
skip-lint = false
seeds = false

[programs.testnet]
seven_seas = "2a4NcnkF5zf14JQXHAv39AsRf7jMFj13wKmTL6ZcDQNd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://gorchain.wstf.io"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[networks.gorbagana]
url = "https://gorchain.wstf.io"
